### PR TITLE
1.17.1 fabric backport of 1.18 plushies

### PR DESCRIPTION
**Pull request by Knife-Moth**
I'm new to github, please forgive me if I'm doing this wrong.

### CODE REVIEW

**Comment by Link4real** [comment]
thank you! 
I will check it out later and come back to you :)

**Comment by Link4real** [comment]
alr your version has some of the old hitboxes and models, so I'll change them but thank you a lot for the backport!
Do you want to be mentioned in the release in the description?

**Comment by Knife-Moth** [comment]
Yes please, thank you!

**Comment by Link4real** [comment]
Alr, it's released!
Thank you once again :)
Here are the links: 
[Modrinth ](https://modrinth.com/mod/plushie/version/v1.2-fabric-1.17.1)
[Curseforge]( https://www.curseforge.com/minecraft/mc-mods/plushie-mod/files/3832569)

**Pull request merged**
