### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by nageih**

### CODE REVIEW

**Comment by Link4real** [comment]
If you are still interested, please add your translation [here](https://poeditor.com/join/project/q0MscdMSrw
)
We would definitely appreciate your help!

**Comment by nageih** [comment]
I'll add my translation later!

**Comment by nageih** [comment]
@Link4real I hava finished Chinese translation on the website!

**Comment by Link4real** [comment]
**Thank you so much!**
You have been a great help!
Thanks to you, the next versions of the mod will be available in _Chinese_!!!

**Pull request closed without merging**
